name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./react

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./react/yarn.lock
        
    - name: Install dependencies
      run: yarn
      
    - name: Build project
      run: yarn build
      
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./react/dist  # Path to your build output directory

  deploy:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
